### ISSUE TITLE
Sharp deprecation warnings

### ISSUE THREAD

**Issue by strarsis** [mahnunchik/gulp-responsive#64] opened 2016-12-23 17:49 UTC
Deprecation warnings from sharp are logged when running gulp-responsive: 
````
[...]
quality: use jpeg({ quality: ... }), webp({ quality: ... }) and/or tiff({ quality: ... }) instead
progressive: use jpeg({ progressive: ... }) and/or png({ progressive: ... }) instead
withoutChromaSubsampling: use jpeg({ chromaSubsampling: "4:4:4" }) instead
compressionLevel: use png({ compressionLevel: ... }) instead
[...]
````

See also at https://github.com/lovell/sharp/blob/master/lib/output.js#L429.

**Comment by Nicholaiii** [comment] 2017-01-25 14:08
Duplicate of #61.

However, I would really like to see this fixed :)

**Closed** 2017-05-25 23:59 UTC
