### ISSUE TITLE
jpeg -> jpg

### ISSUE THREAD

**Issue by Alexufo** [mahnunchik/gulp-responsive#118] opened 2019-03-30 02:01 UTC
extname: '.jpg' always return 'jpeg' in file name. How I can disable it?

**Comment by idiazroncero** [comment] 2019-04-08 15:57
I had the same issue and solved it by manually patching this project.

I used patch-package, and it's as easy as this: 

- Add (patch-package)[https://www.npmjs.com/package/patch-package] to your repo: `yarn add patch-package postinstall-postinstall`
- Go to /node_modules/gulp-responsive/lib/format.js and modify line 11 to `return 'jpg'` instead of `jpeg`
- Execute `yarn patch-package gulp-responsive`. This will automagically generate a patch with your changes.
- Now, everytime you add / install / rebuild / delete / upgrade your `node_modules` and it affects gulp-responsive, the patch will be applied to ensure everything keeps working as intended.

**Comment by s8m2s** [comment] 2019-04-17 22:01
same issue here

**Comment by artlili** [comment] 2019-06-23 12:27
I used gulp-if and gulp-rename

$.gulp.task('responsive', () => {
    return $.gulp.src('./dev/static/images/**/*.{jpg,png,webp}')
      .pipe($.gp.responsive({
        '**/*': [{
          width: '50%',
        },
        {
          width: '100%',
          rename: { suffix: '@2x' },

        }]
      }, {
        quality: 70,
        progressive: true,
        withMetadata: false,
        errorOnEnlargement: false,
      }))
      .pipe($.gp.if(file => {
        return file.path.match('.jpeg') },
        $.gp.rename({extname: ".jpg"
      })))
      .pipe($.gulp.dest('./build/images/'));
  });

**Comment by artlili** [comment] 2019-06-23 12:29
I used gulp-if and gulp-rename

`$.gulp.task('responsive', () => {
    return $.gulp.src('./dev/static/images/**/*.{jpg,png,webp}')
      .pipe($.gp.responsive({
        '**/*': [{
          width: '50%',
        },
        {
          width: '100%',
          rename: { suffix: '@2x' },

        }]
      }, {
        quality: 70,
        progressive: true,
        withMetadata: false,
        errorOnEnlargement: false,
      }))
      .pipe($.gp.if(file => {
        return file.path.match('.jpeg') },
        $.gp.rename({extname: ".jpg"
      })))
      .pipe($.gulp.dest('./build/images/'));
  });`

**Comment by artlili** [comment] 2019-06-23 12:31
I used gulp-if and gulp-rename

```
$.gulp.task('@2x', () => {
    return $.gulp.src('./dev/static/images/**/*.{jpg,png,webp}')
      .pipe($.gp.responsive({
        '**/*': [{
          width: '50%',
        },
        {
          width: '100%',
          rename: { suffix: '@2x' },

        }]
      }, {
        quality: 70,
        progressive: true,
        withMetadata: false,
        errorOnEnlargement: false,
      }))
      .pipe($.gp.if(file => {
        return file.path.match('.jpeg') },
        $.gp.rename({extname: ".jpg"
      })))
      .pipe($.gulp.dest('./build/images/'));
  });
```

**Comment by s1awek** [comment] 2019-08-01 10:36
Just add `format: 'jpg'`, eg.:
`{
    width: '50%',
    format: 'jpg',
 }`

**Comment by StarpTech** [comment] 2019-10-11 13:55
Fixed in https://github.com/mahnunchik/gulp-responsive/pull/129

**Closed by StarpTech** 2019-10-11 13:55 UTC
